package rpg_database.character_sheet.common;

public enum Keys {
	ARMOR_PENALTY, ARMOR_RATING, ARMOR_TYPE, ATTRIBUTE_REQUIREMENTS, BASE_CLASS, BASE_CLASSES_ARRAY, FIELD, FOCUSES, LANGUAGES_ARRAY,
	MAJOR_ATTRIBUTES_ARRAY, RESTRICTED_BACKGROUNDS, STRAIN, VALUE, WEAPON_GROUPS, RACES_ARRAY;

}
